API_PREFIX = "api"

# apps:
CREW = "crew"
ROLES = "roles"
ACCOUNTS = "accounts"
SIGNUP = "signup"
LOGIN = "login"
LOGOUT = "logout"
REFRESH_TOKEN = "token/refresh"
USER_INFO = "user"
CLIENTS = "clients"

# app urls:
SIGNUP_URL = f"{API_PREFIX}/{ACCOUNTS}/{SIGNUP}/"
LOGIN_URL = f"{API_PREFIX}/{ACCOUNTS}/{LOGIN}/"
LOGOUT_URL = f"{API_PREFIX}/{ACCOUNTS}/{LOGOUT}/"
REFRESH_TOKEN_URL = f"{API_PREFIX}/{REFRESH_TOKEN}/"
USER_INFO_URL = f"{API_PREFIX}/{ACCOUNTS}/{USER_INFO}/"
ROLES_URL = f"{API_PREFIX}/{ROLES}/"
CREW_URL = f"{API_PREFIX}/{CREW}/"
CLIENTS_URL = f"{API_PREFIX}/{CLIENTS}/"
