# Generated by Django 5.2.1 on 2025-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crew_hourly_wage_crew_is_active_crew_is_tasked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='hourly_wage',
            field=models.IntegerField(default=0),
        ),
    ]
