# Generated by Django 5.2.1 on 2025-05-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('crew', '0004_crew_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_members', to='clients.client'),
        ),
    ]
